

We will work on iris database. 

This is just a keras basics - like a revision. 

In [10]:
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [19]:
type(iris)

sklearn.utils._bunch.Bunch

In [20]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [14]:
X = iris.data

In [15]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
y = iris.target

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

We will convert this to one hot encoding. 

In [21]:
from keras.utils import to_categorical

C:\Users\Asus\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [22]:
y = to_categorical(y)

In [23]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [24]:
from sklearn.model_selection import train_test_split

In [29]:
X.shape

(150, 4)

In [30]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 42)

In [31]:
from sklearn.preprocessing import MinMaxScaler

In [32]:
scaler = MinMaxScaler()
scaler.fit(x_train)
scaled_x_train = scaler.transform(x_train)
scaled_x_test = scaler.transform(x_test)

In [33]:
from keras.models import Sequential
from keras.layers import Dense 

In [34]:
model = Sequential()

In [35]:
model.add(Dense(8, input_dim = 4, activation='relu'))
model.add(Dense(8, input_dim = 4, activation='relu'))
model.add(Dense(3,activation='softmax'))

C:\Users\Asus\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [36]:
model

<Sequential name=sequential, built=True>

In [37]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [38]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 139 (556.00 B)

 Trainable params: 139 (556.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.fit(scaled_x_train, y_train, epochs = 150, verbose=2)

Epoch 1/150
4/4 - 1s - 312ms/step - accuracy: 0.2952 - loss: 1.2117
Epoch 2/150
4/4 - 0s - 16ms/step - accuracy: 0.2952 - loss: 1.2009
Epoch 3/150
4/4 - 0s - 14ms/step - accuracy: 0.2952 - loss: 1.1918
Epoch 4/150
4/4 - 0s - 15ms/step - accuracy: 0.2952 - loss: 1.1829
Epoch 5/150
4/4 - 0s - 16ms/step - accuracy: 0.2952 - loss: 1.1744
Epoch 6/150
4/4 - 0s - 14ms/step - accuracy: 0.2952 - loss: 1.1652
Epoch 7/150
4/4 - 0s - 26ms/step - accuracy: 0.2952 - loss: 1.1569
Epoch 8/150
4/4 - 0s - 16ms/step - accuracy: 0.2952 - loss: 1.1485
Epoch 9/150
4/4 - 0s - 15ms/step - accuracy: 0.2952 - loss: 1.1407
Epoch 10/150
4/4 - 0s - 13ms/step - accuracy: 0.2952 - loss: 1.1331
Epoch 11/150
4/4 - 0s - 14ms/step - accuracy: 0.2952 - loss: 1.1260
Epoch 12/150
4/4 - 0s - 14ms/step - accuracy: 0.2952 - loss: 1.1190
Epoch 13/150
4/4 - 0s - 14ms/step - accuracy: 0.2952 - loss: 1.1122
Epoch 14/150
4/4 - 0s - 14ms/step - accuracy: 0.2952 - loss: 1.1052
Epoch 15/150
4/4 - 0s - 13ms/step - accuracy: 0.2952 - l

In [42]:
predictions = model.predict(scaled_x_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


In [47]:
y_pred = [x.argmax() for x in predictions]

In [49]:
y_pred[3]

np.int64(1)

In [51]:
y_test = y_test.argmax(axis=1)

In [52]:
y_test[3]

np.int64(1)

In [53]:
from sklearn.metrics import confusion_matrix , classification_report, accuracy_score

In [54]:
print(confusion_matrix(y_test, y_pred))

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [55]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [56]:
print(accuracy_score(y_test, y_pred))

0.9777777777777777


We will now save and load the model 

In [57]:
model.save("L:/Workspace/Models/irisdlmodel.h5")

In [58]:
from keras.models import load_model

In [59]:
new_model = load_model("L:/Workspace/Models/irisdlmodel.h5")