What is topic modeling - 
it allows us to efficiently analyzer large volumnes of text by clustering documents into topics. 
    A large amount of text data is unlabeled, meaning we wont be apply to apply our previous supervised learning approaches ,

`m
If we have unlabeled data, then we can attempt to discover labels. 
In that case of text datam this means attemptng to discover the clusters of documents, grouped together by topic 

We dont give exact topics - we only cluster them. Topic - we can decide 

We will see how Latent Dirichlet Allocation works - LDA 

Assumptions - 
Documents with simiklar topics use similar grp of words
Latent topics can then be found by searching for group of words that frequently occur together in documents accorss the corpus 

# How LDA works? 
We have a few documents. 
We decide a 'k' - number of topics - we decide it for now. 
Then we go through each document, and randomy assign each word in the document to one of the k topics. 
This gives us word distributions and topic representations. 

Then - we iterate over every word in every document, for each topic t, 
we get 
p(topic t | document d) = proportion of words in document d that are currently assigned to topic t
We get p(word w | topic t) = the proportion of assignments to topic t over all documents that come from this word w 
then we re-assign w - a new topic, where we choose t with probability p(topic t| document d) * p(word w | topic t)

This is probability that topic t generated word w
Then we have each document assigned t a topic. 
Then though it, we can find common words for each topic. "

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("L:\\Workspace\\Resources\\UPDATED_NLP_COURSE\\05-Topic-Modeling\\npr.csv" , sep = "\t")

In [4]:
df.head()

,Article
0,"In the Washington of 2016, even when the polic..."
1,Donald Trump has used Twitter — his prefe...
2,Donald Trump is unabashedly praising Russian...
3,"Updated at 2:50 p. m. ET, Russian President Vl..."
4,"From photography, illustration and video, to d..."


In [5]:
print(df.iloc[0])

Article    In the Washington of 2016, even when the polic...
Name: 0, dtype: object


In [7]:
# df['Article'][0]

In [8]:
len(df)

11992

In [9]:
df.isnull().sum()

Article    0
dtype: int64

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer(max_df=0.9, min_df = 2, stop_words = 'english')
# it will discard words that show up in 90% of documents. That means theya re too common - and are in all the topics. 
#  min_df = word should be in at least this number of or ratio of documents

In [12]:
dtm = cv.fit_transform(df['Article'])

In [13]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3033388 stored elements and shape (11992, 54777)>

In [14]:
from sklearn.decomposition import LatentDirichletAllocation

In [15]:
lda = LatentDirichletAllocation(n_components=7, random_state=42)

In [16]:
 lda.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [18]:
# Grab the vocab of words
len(cv.get_feature_names_out())

#  Grab the topics 


#  Grab the highest probability words per topcs 

54777

In [19]:
type(cv.get_feature_names_out())

numpy.ndarray

In [32]:
cv.get_feature_names_out()[41000]

'reproductive'

In [35]:
import random

random_word_id = random.randint(0,54777)
cv.get_feature_names_out()[random_word_id]

'gamesmanship'

In [38]:
len(lda.components_)

7

In [39]:
lda.components_.shape

(7, 54777)

In [40]:
single_topic = lda.components_[0]

In [41]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

What does argssort does??? 

In [42]:
import numpy as np
arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [43]:
arr.argsort()

array([2, 0, 1])

So it sorts and then sends us the original index of the numbers 

In [44]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

for this topic, we got 10 highest probability words 

In [52]:
top_ten_words = single_topic.argsort()[-20:]
top_ten_words

array([38079, 46581, 48643, 25406, 50426, 10421, 32089, 54403, 18349,
           1, 33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673,
       42561, 42993])

In [53]:
for index in top_ten_words:
    print(cv.get_feature_names_out()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


As we can see it is more to do with government - 

In [55]:
for index, topic in enumerate(lda.components_):
    print(f"The topc 15 words for topic number {index}")
    print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print("\n\n")

The topc 15 words for topic number 0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']



The topc 15 words for topic number 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']



The topc 15 words for topic number 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']



The topc 15 words for topic number 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']



The topc 15 words for topic number 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']



The topc 15 words for topic number 5
['years', 'going', 've', 'life', 'don', 'new', 'wa

Now we attach this lda with words or documents 

In [57]:
df

,Article
0,"In the Washington of 2016, even when the polic..."
1,Donald Trump has used Twitter — his prefe...
2,Donald Trump is unabashedly praising Russian...
3,"Updated at 2:50 p. m. ET, Russian President Vl..."
4,"From photography, illustration and video, to d..."
...,...
11987,The number of law enforcement officers shot an...
11988,"Trump is busy these days with victory tours,..."
11989,It’s always interesting for the Goats and Soda...
11990,The election of Donald Trump was a surprise to...


In [58]:
topic_res = lda.transform(dtm)

In [59]:
dtm

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3033388 stored elements and shape (11992, 54777)>

In [61]:
topic_res.shape

(11992, 7)

In [64]:
topic_res[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [65]:
df['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

We can see topic index 1 was realted to politics or government - and its true as we can see through the actual article of that number. It is of politics. 

LDA Dont give us topic name - it gives us which article belongs to which number topic - it groups the documents of similar topic - but to name them is our choice 